info:
  name: update_settings
  type: http
  seq: 2

http:
  method: patch
  url: http://{{host}}:{{port}}/api/settings
  headers:
    - name: Authorization
      value: Bearer {{token}}
    - name: Content-Type
      value: application/json
  body:
    type: json
    data: |-
      {
        "updates": {
          "some_key": "some_value"
        }
      }
  auth: inherit

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
