info:
  name: create_task
  type: http
  seq: 2

http:
  method: post
  url: http://{{host}}:{{port}}/api/projects/{{projectId}}/tasks
  headers:
    - name: Authorization
      value: Bearer {{token}}
    - name: Content-Type
      value: application/json
  body:
    type: json
    data: |-
      {
        "title": "Create a GitHub repository",
        "description": "Create a Github repository named hello-world-app",
        "status": "backlog"
      }
  auth: inherit

runtime:
  variables:
    - name: projectId
      value: 8036e83e-a0dc-4b36-92b5-9471998630fb
    - name: token
      value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXNoYm9hcmQiLCJpYXQiOjE3NzUzOTE5NjcsImV4cCI6MTc3Nzk4Mzk2N30._50wonQpSMoWrPVhYUK1h7YcYZJumSBibKEifPN2JRw

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
