info:
  name: get_task
  type: http
  seq: 1

http:
  method: get
  url: http://{{host}}:{{port}}/api/projects/{{projectId}}/tasks/{{taskId}}
  headers:
    - name: Authorization
      value: Bearer {{token}}
  auth: inherit

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
