info:
  name: get_task
  type: http
  seq: 1

http:
  method: get
  url: http://{{host}}:{{port}}/api/projects/{{projectId}}/tasks/{{taskId}}
  headers:
    - name: Authorization
      value: Bearer {{token}}
  auth: inherit

runtime:
  variables:
    - name: projectId
      value: 1e1e303d-3ac3-4ace-ad4c-918acf370dab

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
