info:
  name: list_tasks
  type: http
  seq: 4

http:
  method: get
  url: http://{{host}}:{{port}}/api/projects/{{projectId}}/tasks
  headers:
    - name: Authorization
      value: Bearer {{token}}
  auth: inherit

runtime:
  variables:
    - name: projectId
      value: 09b1b5af-113c-4903-a669-d4395c5d7e58
    - name: token
      value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXNoYm9hcmQiLCJpYXQiOjE3NzU2OTA5NjcsImV4cCI6MTc3ODI4Mjk2N30.iEKsUPwO6hVkkY92JfoPzI1-u2jf5Ye40JWwl8Nw_S8

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
