info:
  name: update_task
  type: http
  seq: 5

http:
  method: patch
  url: http://{{host}}:{{port}}/api/projects/{{projectId}}/tasks/{{taskId}}
  headers:
    - name: Authorization
      value: Bearer {{token}}
    - name: Content-Type
      value: application/json
  body:
    type: json
    data: |-
      {
        "status": "doing"
      }
  auth: inherit

runtime:
  variables:
    - name: projectId
      value: 1e1e303d-3ac3-4ace-ad4c-918acf370dab
    - name: taskId
      value: f5608867-cdad-4361-a62c-fc3fd39b6bf3
    - name: token
      value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXNoYm9hcmQiLCJpYXQiOjE3NzU3MDI3MTMsImV4cCI6MTc3ODI5NDcxM30.JrZTNkcE92nnh3HkJ-neRRE8EwpVK0JhLC7MM5hI0wY

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
